<Project Sdk="Microsoft.Build.NoTargets">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <BenchmarkTarget Include="Apache.Calcite.Cosmos.Benchmarks|net8.0" ProjectName="Apache.Calcite.Cosmos.Benchmarks" TargetFramework="net8.0" />
        <BenchmarkTarget Include="Apache.Calcite.Cosmos.Benchmarks|net10.0" ProjectName="Apache.Calcite.Cosmos.Benchmarks" TargetFramework="net10.0" />
    </ItemGroup>

    <Target Name="GetCopyToOutputDirectoryItemsByBenchmarkTarget" BeforeTargets="BeforeBuild" Inputs="@(BenchmarkTarget)" Outputs="%(Identity)\null">

        <PropertyGroup>
            <_ProjectName>%(BenchmarkTarget.ProjectName)</_ProjectName>
            <_ProjectFile>%(BenchmarkTarget.ProjectFile)</_ProjectFile>
            <_ProjectFile Condition=" '$(_ProjectFile)' == '' And Exists('..\$(_ProjectName)\$(_ProjectName).csproj') ">..\$(_ProjectName)\$(_ProjectName).csproj</_ProjectFile>
            <_ProjectFile Condition=" '$(_ProjectFile)' == '' And Exists('..\$(_ProjectName)\$(_ProjectName).msbuildproj') ">..\$(_ProjectName)\$(_ProjectName).msbuildproj</_ProjectFile>
            <_TargetFramework>%(BenchmarkTarget.TargetFramework)</_TargetFramework>
        </PropertyGroup>

        <ItemGroup>
            <PublishProjectReference Include="$(_ProjectFile)">
                <SetTargetFramework>TargetFramework=$(_TargetFramework)</SetTargetFramework>
                <PublishTargetPath>$(_ProjectName)\$(_TargetFramework)</PublishTargetPath>
                <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
                <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            </PublishProjectReference>
        </ItemGroup>
    </Target>

</Project>
