<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
        <RootNamespace>Apache.Calcite.Cosmos.Benchmarks</RootNamespace>
        <Optimize Condition=" '$(Configuration)' == 'Release' ">true</Optimize>
        <ServerGarbageCollection>false</ServerGarbageCollection>
        <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="IKVM" Version="8.16.0" />
        <PackageReference Include="IKVM.Java.Extensions" Version="8.16.0" />
        <PackageReference Include="IKVM.Maven.Sdk" Version="1.12.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Apache.Calcite.Extensions" Version="2.0.1-pre.64" />
    </ItemGroup>

    <ItemGroup>
        <MavenReference Include="org.apache.calcite:calcite-core" Version="1.42.0" />
        <MavenReference Include="org.apache.calcite.avatica:avatica-core" Version="1.28.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Apache.Calcite.Cosmos.Adapter\Apache.Calcite.Cosmos.Adapter.csproj" />
    </ItemGroup>

</Project>
